language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get install python3-dev libusb-1.0-0-dev libudev-dev
  - pip install https://github.com/ArkEcosystem/arky/archive/aip11.zip
  - pip install -r requirements.txt
script:
  - python -m unittest discover
os:
  - linux