sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install https://github.com/ArkEcosystem/arky/archive/aip11.zip
  - pip install -r requirements.txt
script:
  - python -m unittest discover
os:
  - linux